### ISSUE TITLE
setup direct db access for unified status

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WorkflowWebTools#116]
following https://github.com/CMSCompOps/WmAgentScripts/pull/337 let's work out a way to read the unified status from where it belongs

**Comment by vlimant** [comment]
as a work around the file is back in place

https://cms-unified.web.cern.ch/cms-unified/public/statuses.json

https://github.com/CMSCompOps/WmAgentScripts/commit/ceda0da63486b57f9b877dc4f65df9e00dec0cab

but should disappear in favor of db access

**Comment by dabercro** [comment]
Reading mostly happens here: https://github.com/CMSCompOps/WorkflowWebTools/blob/master/workflowwebtools/errorutils.py#L24

Dima sent me an example of how to connect, so I'm trying out this change at the moment: https://github.com/dabercro/WorkflowWebTools/blob/oracle/workflowwebtools/errorutils.py#L44

**Comment by dabercro** [comment]
This is working, but there is too long of a delay between when workflows show up in the database (and unified's webpage) and when they show up on this webpage.

**Comment by vlimant** [comment]
which "this webpage" ? the wtc-console ?

**Comment by dabercro** [comment]
Yeah, the WorkflowWebTools generated page. I just updated the server to make the refresh period configurable and shortened it from half an hour to five minutes.
