### ISSUE TITLE
update ES query for showlog

### ISSUE THREAD

**Issue by vlimant** [CMSCompOps/WorkflowWebTools#128]
@dabercro I don't recall where the php for showlog is but 

https://cms-unified.web.cern.ch/cms-unified/showlog/?search=critical&module=assignor

 does  not show anything by default. I think the ES query needs to be updated to have the proper filtering done on the es-server side instead of the client.
 We can update the schema of the es documents if needed

**Comment by dabercro** [comment]
I never knew where it ended up being moved to either. It looks like I got rid of my copy because it had authentication stuff in it. Try `/eos/home-c/cmsunified/www/showlog` maybe? I don't have permissions to look. If it's not there, I'm sure it's listed in the cms-unified account settings.

**Comment by vlimant** [comment]
ended up here https://github.com/CMSCompOps/WmAgentScripts/commit/caa3367b67630bc64771a28dad909b5080a7b92c 
I added the more economical search on module == subject
