### ISSUE TITLE
Error explained improvement

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WorkflowWebTools#24]
For example, I am checking this workflow
https://vocms0113.cern.ch:80/seeworkflow?workflow=pdmvserv_SUS-RunIISpring16FSPremix-00086_00047_v0__170116_081631_4724
I am interested in error 8001, so I click on the 8001 link in the summary table. we get this
https://vocms0113.cern.ch:80/explainerror?errorcode=8001&workflowstep=/pdmvserv_SUS-RunIISpring16FSPremix-00086_00047_v0__170116_081631_4724/Production
Those are the explanations of all 8001 exit codes for every workflow in assistance. 
How can I know which is the explanation for the current workflow?

**Comment by dabercro** [comment]
Okay, that should be easy for me to add in. I already have this function here that seems to do the trick: https://github.com/CMSCompOps/OpsSpace/blob/master/CMSToolBox/workflowinfo.py#L71-L94 I just have to make sure the format is the same.

**Comment by dabercro** [comment]
#27 now has it set that any link to the error code from a workflow details page will only show errors for that workflow. (From the jobdetail page: https://github.com/CMSCompOps/OpsSpace/blob/048366ea2c19496f42eb2d59e29667db9f68ccb4/CMSToolBox/workflowinfo.py#L255-L257). Accessing the error explanations from the global view still shows all the errors from Jean-Roch's explanations.json. This is a nice step to phasing that out though. Let me know if that setup is enough for me to close this ticket then.

**Comment by prozober** [comment]
Now that there are workflows in assistance again, I've checked this change. Everything is OK, the links provide the info we need. We can close this issue.
