### ISSUE TITLE
Number of messages on Unified critical page

### ISSUE THREAD

**Issue by areinsvo** [CMSCompOps/WorkflowWebTools#29]
Not super important, but I'm curious @dabercro :
What constraints are there on the number of messages shown on the Unified critical page? Right now, there are only 12 messages showing up, regardless of the number I put in for "Logs Limit". Normally there are more messages, but there always seems to be a limit to how many messages will show, unaffected by what Logs Limit is set to. (ie if I say 100, then 100 are shown, but if I increase it to 200, it still only shows ~100, and increasing Logs Limit more does nothing)

**Comment by dabercro** [comment]
The limit just sets an upper limit. If the number of logs coming back from the elastic search request is fewer, than more won't show up.

The number coming back from elastic search is determined by the size, I think: https://github.com/dabercro/UnifiedWebpagesInstaller/blob/master/showlog/showlog.py#L34 I can make this size a changeable number in case the elastic search machine is flooded by irrelevant (in this case, non-critical) logs. Are you using the instance on AFS?

**Comment by areinsvo** [comment]
This is the page I look at for the critical messages: http://dabercro.web.cern.ch/dabercro/unified/showlog/?search=critical
Just increasing the size of the elastic search would probably be enough, if making it changeable is too difficult. Most of the time it is fine, as long as I have been looking at the critical page often enough to catch all the messages as they come in.

**Comment by dabercro** [comment]
I'll make it adjustable just in case. I'll let you know when it's updated.

**Comment by dabercro** [comment]
This change should do the trick: https://github.com/dabercro/UnifiedWebpagesInstaller/compare/170fba410f...3c46ca6d91 Now there is a fourth field for "Elastic Search Size" in case you're not getting enough logs. Be careful making the number too big, or you'll get an error.

**Comment by areinsvo** [comment]
Thanks Dan! Any guidelines on what "too big" means?

**Comment by dabercro** [comment]
It I try to expand the size to 100,000, for example, the elastic search doesn't return. You'll just see a 500 page. 10,000 is fine though, and that's already 10 times as many logs as it searches by default.

**Comment by areinsvo** [comment]
Thanks! This will help a lot. I don't think we need to keep this issue open any longer.
