### ISSUE TITLE
Moving to vocms049

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WorkflowWebTools#37]
We better separate this request https://github.com/CMSCompOps/WorkflowWebTools/issues/6#issuecomment-288681807, don't you think?

**Comment by dabercro** [comment]
That's probably a good idea. Let me ping @vlimant again.

Copied from previous reply:

When working on vocms0113 though, I had trouble getting mod_wsgi compiled for Python 2.7. Would you want to set that up on vocms049, or should we just use the built in Cherrypy server and only open the used port to CERN addresses?

**Comment by dabercro** [comment]
Everything was installed on vocms049 with explicit instructions on how to run, but the server was never started. Now it sounds like that particular machine is being decommissioned.
