### ISSUE TITLE
Following up the kill and clone action

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WorkflowWebTools#54]
Today I was testing the "kill and clone: action for workflows with >0 ACDC rounds and I saw something weird. 
We agreed that the recovery tool would provide the list of ACDCs we need to reject when the kill and clone option is selected, right? 
We can have something like this:

- Original workflow
  - First ACDC round.
    - Second ACDC round.
      - Third ACDC round.

1. So, The operator will check the third ACDC round to make the decision of "kill and clone", and of course we can have N ACDCs belonging to the third round.
2. But, if the operator selects "kill and clone" from any of the ACDCs (no matter the # round), even from the original workflow, the tool should provide in any case, the list of all ACDCs we need to reject. 
3. From the Unified side, the original workflow must be cloned using the parameter the operator is providing.

**Comment by dabercro** [comment]
If I understand you, the problem with the current setup is that the tool only includes ACDCs newer than the selected workflow or ACDC in the list of ACDCs. You want this check to be disabled for "kill and clone," right? Should I also disable the "Resubmission" check too in order to include the original workflow if an ACDC is selected, or should I include the original workflow in the action document?

**Comment by prozober** [comment]
Yes, we should disable kill and clone for ACDCs. I think that would be enough.
BTW, could you please delete the action I send for areinsvo_ACDC0_task_TOP-RunIISummer15wmLHEGS-00213__v1_T_170616_164109_5082. Thanks.

**Comment by dabercro** [comment]
Okay, I can disable the option easily enough.

The action is removed.

**Comment by dabercro** [comment]
So I made a PR that just removes the 'clone' option from every page where the type is Resubmission. Do you think this will do what you want? #56 If yes, I'll merge it and update the server.

**Comment by prozober** [comment]
Please, go ahead.
