### ISSUE TITLE
Interface for special actions

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WorkflowWebTools#58]
As discussed in your main issue
https://github.com/CMSCompOps/WorkflowWebTools/issues/6#issuecomment-312073860
we need to start thinking about a separated interface where we can take specials action over the workflows. Those actions should not be automatized.
The special actions so far are:
1. By-pass.
2. Force-complete: this is kind of different because the action should be taken over active workflows, I mean, workflows that are currently running.

**Comment by dabercro** [comment]
Okay, I'm thinking I can put these as options under the "Other action" option. Does that sound separate enough? I'll leave the "other" textbox for fun, but add another set of options for by-pass and force-complete.

**Comment by dabercro** [comment]
#59 is an example of this. Testing the output on my desktop gives me something that looks like this: 

``{"fabozzi_Run2016H-v1-ZeroBiasIsolatedBunch5-09Nov2016_8023_161109_181336_2225": {"Action": "special", "Reasons": [], "ACDCs": ["prozober_ACDC0_Run2016H-v1-ZeroBiasIsolatedBunch5-09Nov2016_8023_161121_093315_8014", "prozober_ACDC0_Run2016H-v1-ZeroBiasIsolatedBunch5-09Nov2016_8023_161121_230507_1607", "prozober_recovery-1-fabozzi_Run2016H-v1-ZeroBiasIsolatedBunch5-09Nov2016_8023__161201_144838_1975", "prozober_recovery-3-fabozzi_Run2016H-v1-ZeroBiasIsolatedBunch5-09Nov2016_8023__161201_144903_1794", "prozober_recovery-2-fabozzi_Run2016H-v1-ZeroBiasIsolatedBunch5-09Nov2016_8023__161201_144853_7563", "prozober_recovery-0-fabozzi_Run2016H-v1-ZeroBiasIsolatedBunch5-09Nov2016_8023__161201_144830_2965"], "user": "dabercro", "Parameters": {"action": "by-pass", "other": ""}}}``

So if "Action" is "special", checking ["Parameters"]["action"] will give the option chosen. Let me know what you think.
