### ISSUE TITLE
Multicore option

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WorkflowWebTools#79]
We need to include the option to change the core count per task.
According to the selected value, Unified should be able to define the memory @X core, right @vlimant? 
So, we need to change the web form as well as the actor to receive this new parameter.
@dabercro @areinsvo

**Comment by dabercro** [comment]
This won't be a problem to add. Do you want it to have discrete options (like 1, 2, 4, or 8 cores, for example) or should I just add a text box?

**Comment by dabercro** [comment]
I guess another question is do we want this option for 'clone', 'acdc', and 'recovery' or just a subset of those?

**Comment by dabercro** [comment]
For now, I added an options list for all the actions listed above with #80

**Comment by prozober** [comment]
Hi Dan, the multicore option needs to be available for all the actions.
For the moment, I think is better to include the multicore option as a textbox. We can go for 1 to ~64 cores.
Now, we need to wait for @areinsvo to include the option at the actor side.

**Comment by dabercro** [comment]
Okay, #81 places them as textboxes

**Comment by areinsvo** [comment]
@prozober for the scaling by memory: If both the memory and multicore options are used, actor will assume that the memory value is NOT scaled by the number of cores. Or more specifically, that the memory value passed is for the **initial** number of cores, and needs to be scaled up to whatever 'multicore' is set to. Does that make sense?

The scaling will be done in the same manner as  https://github.com/CMSCompOps/WmAgentScripts/blob/5c0c238562af864091e5a664a4d9d0591e111158/Unified/recoveror.py#L106 

The script has been updated and the new feature is ready to be tested. We'll have to pay close attention to it the first couple times the multicore parameter is used.

**Comment by prozober** [comment]
Hi @areinsvo, that makes sense. I will let you know when I have a request to test.
