### ISSUE TITLE
secondary_xrootd option isn't working

### ISSUE THREAD

**Issue by prozober** [CMSCompOps/WorkflowWebTools#84]
@areinsvo, It seems the option is not working on the actor side.
I sent this action: 
"mcremone_ACDC0_task_HIN-pp502Fall15-00165__v1_T_171114_105324_4155": {"Action": "acdc", "Reasons": [], "ACDCs": ["mcremone_ACDC0_task_HIN-pp502Fall15-00165__v1_T_171114_105332_8534"], "user": "prozober", "Parameters": {"HIN-HINppWinter16DR-00164_0": {"cores": "", "memory": "", "sites": ["T2_UK_London_Brunel", "T2_UK_London_IC", "T2_UK_SGrid_RALPP"], "secondary": "enabled"}}}

This workflow was created 
https://cmsweb.cern.ch/reqmgr2/fetch?rid=mcremone_ACDC1_task_HIN-pp502Fall15-00165__v1_T_171115_112736_5959
with
"TrustPUSitelists": false

Could you please take a look?

**Comment by areinsvo** [comment]
For some reason I either forgot to implement "secondary" or I never realized that it was an option that actor needed to be able to handle. Regardless, it has been implemented now. Please double check that it works as expected next time you send an action with that parameter.
